name = "MapBroadcast"
uuid = "ebd9b9da-f48d-417c-9660-449667d60261"
version = "0.1.14"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"

[compat]
BlockArrays = "1.3"
Compat = "4.16"
FillArrays = "1.13"
julia = "1.10"
